import { createStore } from 'vuex'
// Импортируйте все ваши модули

const store = createStore({
    modules: {
        // Здесь перечислите все ваши модули
    },
    state() {
        return {
            nextArrowInBtn:`<svg width="7.946907" height="15.379517" viewBox="0 0 7.94691 15.3795" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' +
              '        <desc>\n' +
              '          Created with Pixso.\n' +
              '        </desc>\n' +
              '        <defs/>\n' +
              '        <path id="Vector" d="M1.00406 14.3755L6.94691 7.68976L1.00406 1.00409" stroke="#292F36" stroke-opacity="1.000000" stroke-width="2.000000" stroke-linejoin="round" stroke-linecap="round"/>\n' +
              '      </svg>`,
            categories: [
                'Bathroom',
                'Bedroom',
                'Kitchen',
                'Living Area'
            ],
            followProjectsData: [
                {
                    name: 'Modern Kitchen',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_1.png')
                },
                {
                    name: 'Modern Kitchen',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_2.png')
                },
                {
                    name: 'Modern Kitchen',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_3.png')
                },
                {
                    name: 'Modern Kitchen',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_4.png')
                }
            ],
            statisticsData: [
                {
                    number: 12,
                    title: 'Years Of Experience'
                },
                {
                    number: 85,
                    title: 'Success Project'
                },
                {
                    number: 15,
                    title: 'Active Project'
                },
                {
                    number: 95,
                    title: 'Happy Customers'
                }
            ],
            articlesAndNewsOptions: [
                {
                isSubtitle: true,
                numberOfTitles: 3,
                titleAlign: 'center',
                },
                {
                    isSubtitle: false,
                    numberOfTitles: 6,
                    titleAlign: 'left',
                }
            ],
            mainPageStartedImgURL: [
                require('../assets/img/start_img.png'),
            ],
            articlesAndNews: [
                {
                  articleId: 1,
                    backgroundImg: require('../assets/img/article_1.png'),
                    name: 'Kitchen Design',
                    title: 'Let’s Get Solution For Building Construction Work',
                    date: '26 December,2022',
                  tag: 'Kitchen',
                  fullImg: require('../assets/img/article_1_full_img.png'),
                },
                {
                  articleId: 2,
                    backgroundImg: require('../assets/img/article_2.png'),
                    name: 'Living Design',
                    title: 'Low Cost Latest Invented Interior Designing\n' +
                        'Ideas.',
                    date: '22 December,2022',
                  tag: 'Bathroom',
                  fullImg: require('../assets/img/article_2_full_img.png'),
                },
                {
                  articleId: 3,
                    backgroundImg: require('../assets/img/article_3.png'),
                    name: 'Interior Design',
                    title: 'Best For Any Office & Business Interior Solution',
                    date: '25 December,2022',
                  tag: 'Building',
                  fullImg: require('../assets/img/article_3_full_img.png'),
                },
                {
                  articleId: 4,
                    backgroundImg: require('../assets/img/article_4.png'),
                    name: 'Kitchen Design',
                    title: 'Let’s Get Solution For Building Construction Work',
                    date: '26 December,2022',
                  tag: 'Kitchen Planning',
                  fullImg: require('../assets/img/article_4_full_img.png'),
                },
                {
                  articleId: 5,
                    backgroundImg: require('../assets/img/article_5.png'),
                    name: 'Living Design',
                    title: 'Low Cost Latest Invented Interior Designing\n' +
                        'Ideas.',
                    date: '22 December,2022',
                  tag: 'Architecture',
                  fullImg: require('../assets/img/article_5_full_img.png'),
                },
                {
                  articleId: 6,
                    backgroundImg: require('../assets/img/article_6.png'),
                    name: 'Interior Design',
                    title: 'Best For Any Office & Business Interior Solution',
                    date: '25 December,2022',
                  tag: 'Bedroom',
                  fullImg: require('../assets/img/article_6_full_img.png'),
                },
              {
                articleId: 7,
                backgroundImg: require('../assets/img/article_1.png'),
                name: 'Kitchen Design',
                title: 'Let’s Get Solution For Building Construction Work',
                date: '26 December,2022',
                tag: 'Kitchen',
                fullImg: require('../assets/img/article_1_full_img.png'),
              },
              {
                articleId: 8,
                backgroundImg: require('../assets/img/article_2.png'),
                name: 'Living Design',
                title: 'Low Cost Latest Invented Interior Designing\n' +
                  'Ideas.',
                date: '22 December,2022',
                tag: 'Bathroom',
                fullImg: require('../assets/img/article_2_full_img.png'),
              },
              {
                articleId: 9,
                backgroundImg: require('../assets/img/article_3.png'),
                name: 'Interior Design',
                title: 'Best For Any Office & Business Interior Solution',
                date: '25 December,2022',
                tag: 'Building',
                fullImg: require('../assets/img/article_3_full_img.png'),
              },
              {
                articleId: 10,
                backgroundImg: require('../assets/img/article_4.png'),
                name: 'Kitchen Design',
                title: 'Let’s Get Solution For Building Construction Work',
                date: '26 December,2022',
                tag: 'Kitchen Planning',
                fullImg: require('../assets/img/article_4_full_img.png'),
              },
              {
                articleId: 11,
                backgroundImg: require('../assets/img/article_5.png'),
                name: 'Living Design',
                title: 'Low Cost Latest Invented Interior Designing\n' +
                  'Ideas.',
                date: '22 December,2022',
                tag: 'Architecture',
                fullImg: require('../assets/img/article_5_full_img.png'),
              },
              {
                articleId: 12,
                backgroundImg: require('../assets/img/article_6.png'),
                name: 'Interior Design',
                title: 'Best For Any Office & Business Interior Solution',
                date: '25 December,2022',
                tag: 'Bedroom',
                fullImg: require('../assets/img/article_6_full_img.png'),
              },
              {
                articleId: 13,
                backgroundImg: require('../assets/img/article_1.png'),
                name: 'Kitchen Design',
                title: 'Let’s Get Solution For Building Construction Work',
                date: '26 December,2022',
                tag: 'Kitchen',
                fullImg: require('../assets/img/article_1_full_img.png'),
              },
              {
                articleId: 14,
                backgroundImg: require('../assets/img/article_2.png'),
                name: 'Living Design',
                title: 'Low Cost Latest Invented Interior Designing\n' +
                  'Ideas.',
                date: '22 December,2022',
                tag: 'Bathroom',
                fullImg: require('../assets/img/article_2_full_img.png'),
              },
              {
                articleId: 15,
                backgroundImg: require('../assets/img/article_3.png'),
                name: 'Interior Design',
                title: 'Best For Any Office & Business Interior Solution',
                date: '25 December,2022',
                tag: 'Building',
                fullImg: require('../assets/img/article_3_full_img.png'),
              },
              {
                articleId: 16,
                backgroundImg: require('../assets/img/article_4.png'),
                name: 'Kitchen Design',
                title: 'Let’s Get Solution For Building Construction Work',
                date: '26 December,2022',
                tag: 'Kitchen Planning',
                fullImg: require('../assets/img/article_4_full_img.png'),
              }
            ],
            largeMainImgs: [
                {
                    imgUrl: require('../assets/img/articles-main.png'),
                    isTitle: true,
                    title:'Articles & News',
                    subtitle:'Home / Blog',
                },
                {
                    imgUrl: require('../assets/img/blog_details_main.png'),
                    isTitle: false,
                    title:'',
                    subtitle:'',
                },
                {
                    imgUrl: require('../assets/img/projects_main.png'),
                    isTitle: true,
                    title: 'Our Project',
                    subtitle: 'Home / Project',
                },
                {
                    imgUrl: require('../assets/img/project_details_main_img.png'),
                    isTitle: false,
                    title:'',
                    subtitle:'',
                }
            ],
            latestPostData: [
                {
                    img: require('../assets/img/latest-post.png'),
                    title: 'Low Cost Latest Invented Interior Designing Ideas',
                    textFirst: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpis dignissim maximus.posuere in.Contrary to popular belief.',
                    textSecond: 'Lorem Ipsum is not simply random text. It has roots in a piece of classica.'
                },
            ],
            articlesList: [
                {
                  articleId: 1,
                    tags: ['Kitchen', 'Kitchen Planning'],
                    firstTitle: 'Let’s Get Solution For Building Construction Work',
                    firstImg: require("../assets/img/kitchen_img_1.png"),
                    date: '26 December,2022',
                    firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                    secondParagraph: 'Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.',
                    secondTitle: 'Design sprints are great',
                    thirdParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                    textList: ['Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                        'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                        'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'],
                    secondImg: require("../assets/img/kitchen_img_2.png"),
                    fourthParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                    quote: true,
                    paragraphList: [
                        'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                        'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                        'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'
                    ],
                },
                {
                  articleId: 2,
                    tags: ['Architecture', 'Kitchen Planning'],
                    firstTitle: 'Low Cost Latest Invented Interior Designing Ideas.',
                    firstImg: require("../assets/img/kitchen_plan.jpg"),
                    date: '26 December,2022',
                    quote: false,
                    firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                },
                {
                  articleId: 3,
                    tags: ['Building', 'Architecture'],
                    firstTitle: 'Best For Any Office & Business Interior Solution',
                    firstImg: require("../assets/img/building.jpg"),
                    date: '26 December,2022',
                    quote: false,
                    firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                },
              {
                articleId: 4,
                tags: ['Kitchen', 'Kitchen Planning'],
                firstTitle: 'Let’s Get Solution For Building Construction Work',
                firstImg: require("../assets/img/kitchen_img_1.png"),
                date: '26 December,2022',
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                secondParagraph: 'Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.',
                secondTitle: 'Design sprints are great',
                thirdParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                textList: ['Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'],
                secondImg: require("../assets/img/kitchen_img_2.png"),
                fourthParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                quote: true,
                paragraphList: [
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'
                ],
              },
              {
                articleId: 5,
                tags: ['Architecture', 'Kitchen Planning'],
                firstTitle: 'Low Cost Latest Invented Interior Designing Ideas.',
                firstImg: require("../assets/img/kitchen_plan.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 6,
                tags: ['Building', 'Architecture'],
                firstTitle: 'Best For Any Office & Business Interior Solution',
                firstImg: require("../assets/img/building.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 7,
                tags: ['Kitchen', 'Kitchen Planning'],
                firstTitle: 'Let’s Get Solution For Building Construction Work',
                firstImg: require("../assets/img/kitchen_img_1.png"),
                date: '26 December,2022',
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                secondParagraph: 'Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.',
                secondTitle: 'Design sprints are great',
                thirdParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                textList: ['Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'],
                secondImg: require("../assets/img/kitchen_img_2.png"),
                fourthParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                quote: true,
                paragraphList: [
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'
                ],
              },
              {
                articleId: 8,
                tags: ['Architecture', 'Kitchen Planning'],
                firstTitle: 'Low Cost Latest Invented Interior Designing Ideas.',
                firstImg: require("../assets/img/kitchen_plan.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 9,
                tags: ['Building', 'Architecture'],
                firstTitle: 'Best For Any Office & Business Interior Solution',
                firstImg: require("../assets/img/building.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 10,
                tags: ['Kitchen', 'Kitchen Planning'],
                firstTitle: 'Let’s Get Solution For Building Construction Work',
                firstImg: require("../assets/img/kitchen_img_1.png"),
                date: '26 December,2022',
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                secondParagraph: 'Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.',
                secondTitle: 'Design sprints are great',
                thirdParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                textList: ['Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'],
                secondImg: require("../assets/img/kitchen_img_2.png"),
                fourthParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                quote: true,
                paragraphList: [
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'
                ],
              },
              {
                articleId: 11,
                tags: ['Architecture', 'Kitchen Planning'],
                firstTitle: 'Low Cost Latest Invented Interior Designing Ideas.',
                firstImg: require("../assets/img/kitchen_plan.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 12,
                tags: ['Building', 'Architecture'],
                firstTitle: 'Best For Any Office & Business Interior Solution',
                firstImg: require("../assets/img/building.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 13,
                tags: ['Kitchen', 'Kitchen Planning'],
                firstTitle: 'Let’s Get Solution For Building Construction Work',
                firstImg: require("../assets/img/kitchen_img_1.png"),
                date: '26 December,2022',
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                secondParagraph: 'Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.',
                secondTitle: 'Design sprints are great',
                thirdParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                textList: ['Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'],
                secondImg: require("../assets/img/kitchen_img_2.png"),
                fourthParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                quote: true,
                paragraphList: [
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'
                ],
              },
              {
                articleId: 14,
                tags: ['Architecture', 'Kitchen Planning'],
                firstTitle: 'Low Cost Latest Invented Interior Designing Ideas.',
                firstImg: require("../assets/img/kitchen_plan.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 15,
                tags: ['Building', 'Architecture'],
                firstTitle: 'Best For Any Office & Business Interior Solution',
                firstImg: require("../assets/img/building.jpg"),
                date: '26 December,2022',
                quote: false,
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
              },
              {
                articleId: 16,
                tags: ['Kitchen', 'Kitchen Planning'],
                firstTitle: 'Let’s Get Solution For Building Construction Work',
                firstImg: require("../assets/img/kitchen_img_1.png"),
                date: '26 December,2022',
                firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                secondParagraph: 'Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.',
                secondTitle: 'Design sprints are great',
                thirdParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                textList: ['Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'],
                secondImg: require("../assets/img/kitchen_img_2.png"),
                fourthParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                quote: true,
                paragraphList: [
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.',
                  'Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.'
                ],
              },
                {
                  articleId: 17,
                    tags: ['Bathroom'],
                    firstTitle: 'Unveiling Tranquility: Crafting Your Dream Bathroom',
                    firstImg: require("../assets/img/bathroom.jpg"),
                    date: '26 December,2022',
                    quote: false,
                    firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                },
                {
                  articleId: 18,
                    tags: ['Bedroom'],
                    firstTitle: 'The Art of Sanctuary: Transforming Your Bedroom Retreat',
                    firstImg: require("../assets/img/bedroom.jpg"),
                    date: '26 December,2022',
                    quote: false,
                    firstParagraph: 'Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don\'t look even slightly believable.',
                },
            ],
            tagList: [
                'Kitchen',
                'Bathroom',
                'Building',
                'Architecture',
                'Kitchen Planning',
                'Bedroom'
            ],
            projectsData: [
                {
                  projectId: 1,
                  name: 'Minimal Bedroom',
                  text:'Decor / Architecture',
                  imgUrl: require('../assets/img/project_img_1.png'),
                  isFavourite: true,
                  tags: ['Bathroom', 'Bedroom'],
                  fullImg: require('../assets/img/project_img_1_full_img.png'),
                },
                {
                  projectId: 2,
                    name: 'Minimal Bedroom',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_2.png'),
                    isFavourite: false,
                    tags: ['Bedroom', 'Kitchen'],
                  fullImg: require('../assets/img/project_img_2_full_img.png'),
                },
                {
                  projectId: 3,
                    name: 'Modern Bedroom',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_3.png'),
                    isFavourite: false,
                    tags: ['Kitchen', 'Living Area'],
                  fullImg: require('../assets/img/project_img_3_full_img.png'),
                },
                {
                  projectId: 4,
                    name: 'Classic Minimal Bedroom',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_4.png'),
                    isFavourite: true,
                    tags: ['Bathroom', 'Living Area'],
                  fullImg: require('../assets/img/project_img_4_full_img.png'),
                },
                {
                  projectId: 5,
                    name: 'Minimal Bedroom table',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_5.png'),
                    isFavourite: false,
                    tags: ['Bathroom', 'Kitchen'],
                  fullImg: require('../assets/img/project_img_5_full_img.png'),
                },
                {
                  projectId: 6,
                    name: 'System Table',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_6.png'),
                    isFavourite: false,
                    tags: ['Bedroom', 'Living Area'],
                  fullImg: require('../assets/img/project_img_6_full_img.png'),
                },
                {
                  projectId: 7,
                    name: 'Modern Bedroom',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_7.png'),
                    isFavourite: false,
                    tags: ['Bathroom', 'Bedroom'],
                  fullImg: require('../assets/img/project_img_7_full_img.png'),
                },
                {
                  projectId: 8,
                    name: 'Modern Bedroom',
                    text:'Decor / Architecture',
                    imgUrl: require('../assets/img/project_img_8.png'),
                    isFavourite: false,
                    tags: ['Kitchen', 'Living Area'],
                  fullImg: require('../assets/img/project_img_8_full_img.png'),
                },
              {
                projectId: 9,
                name: '111Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_1.png'),
                isFavourite: true,
                tags: ['Bathroom', 'Bedroom'],
                fullImg: require('../assets/img/project_img_1_full_img.png'),
              },
              {
                projectId: 10,
                name: '111Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_2.png'),
                isFavourite: false,
                tags: ['Bedroom', 'Kitchen'],
                fullImg: require('../assets/img/project_img_2_full_img.png'),
              },
              {
                projectId: 11,
                name: '111Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_3.png'),
                isFavourite: false,
                tags: ['Kitchen', 'Living Area'],
                fullImg: require('../assets/img/project_img_3_full_img.png'),
              },
              {
                projectId: 12,
                name: '111Classic Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_4.png'),
                isFavourite: true,
                tags: ['Bathroom', 'Living Area'],
                fullImg: require('../assets/img/project_img_4_full_img.png'),
              },
              {
                projectId: 13,
                name: '111Minimal Bedroom table',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_5.png'),
                isFavourite: false,
                tags: ['Bathroom', 'Kitchen'],
                fullImg: require('../assets/img/project_img_5_full_img.png'),
              },
              {
                projectId: 14,
                name: '111System Table',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_6.png'),
                isFavourite: false,
                tags: ['Bedroom', 'Living Area'],
                fullImg: require('../assets/img/project_img_6_full_img.png'),
              },
              {
                projectId: 15,
                name: '111Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_7.png'),
                isFavourite: false,
                tags: ['Bathroom', 'Bedroom'],
                fullImg: require('../assets/img/project_img_7_full_img.png'),
              },
              {
                projectId: 16,
                name: '111Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_8.png'),
                isFavourite: false,
                tags: ['Kitchen', 'Living Area'],
                fullImg: require('../assets/img/project_img_8_full_img.png'),
              },
              {
                projectId: 17,
                name: '222Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_1.png'),
                isFavourite: true,
                tags: ['Bathroom', 'Bedroom'],
                fullImg: require('../assets/img/project_img_1_full_img.png'),
              },
              {
                projectId: 18,
                name: '222Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_2.png'),
                isFavourite: false,
                tags: ['Bedroom', 'Kitchen'],
                fullImg: require('../assets/img/project_img_2_full_img.png'),
              },
              {
                projectId: 19,
                name: '222Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_3.png'),
                isFavourite: false,
                tags: ['Kitchen', 'Living Area'],
                fullImg: require('../assets/img/project_img_3_full_img.png'),
              },
              {
                projectId: 20,
                name: '222Classic Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_4.png'),
                isFavourite: true,
                tags: ['Bathroom', 'Living Area'],
                fullImg: require('../assets/img/project_img_4_full_img.png'),
              },
              {
                projectId: 21,
                name: '222Minimal Bedroom table',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_5.png'),
                isFavourite: false,
                tags: ['Bathroom', 'Kitchen'],
                fullImg: require('../assets/img/project_img_5_full_img.png'),
              },
              {
                projectId: 22,
                name: '222System Table',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_6.png'),
                isFavourite: false,
                tags: ['Bedroom', 'Living Area'],
                fullImg: require('../assets/img/project_img_6_full_img.png'),
              },
              {
                projectId: 23,
                name: '222Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_7.png'),
                isFavourite: false,
                tags: ['Bathroom', 'Bedroom'],
                fullImg: require('../assets/img/project_img_7_full_img.png'),
              },
              {
                projectId: 24,
                name: '222Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_8.png'),
                isFavourite: false,
                tags: ['Kitchen', 'Living Area'],
                fullImg: require('../assets/img/project_img_8_full_img.png'),
              },
              {
                projectId: 25,
                name: 'Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_1.png'),
                isFavourite: true,
                tags: ['Bathroom', 'Bedroom'],
                fullImg: require('../assets/img/project_img_1_full_img.png'),
              },
              {
                projectId: 26,
                name: 'Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_2.png'),
                isFavourite: false,
                tags: ['Bedroom', 'Kitchen'],
                fullImg: require('../assets/img/project_img_2_full_img.png'),
              },
              {
                projectId: 27,
                name: 'Modern Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_3.png'),
                isFavourite: false,
                tags: ['Kitchen', 'Living Area'],
                fullImg: require('../assets/img/project_img_3_full_img.png'),
              },
              {
                projectId: 28,
                name: 'Classic Minimal Bedroom',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_4.png'),
                isFavourite: true,
                tags: ['Bathroom', 'Living Area'],
                fullImg: require('../assets/img/project_img_4_full_img.png'),
              },
              {
                projectId: 29,
                name: 'Minimal Bedroom table',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_5.png'),
                isFavourite: false,
                tags: ['Bathroom', 'Kitchen'],
                fullImg: require('../assets/img/project_img_5_full_img.png'),
              },
              {
                projectId: 30,
                name: 'System Table',
                text:'Decor / Architecture',
                imgUrl: require('../assets/img/project_img_6.png'),
                isFavourite: false,
                tags: ['Bedroom', 'Living Area'],
                fullImg: require('../assets/img/project_img_6_full_img.png'),
              },
            ],
            projectDetailsText: [
                {
                    title:'Minimal Look Bedrooms',
                    text: {
                        text1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquamsem vitae turpis dignissim maximus. Aliquam sollicitudin tellumassa, vbel maximus purus posuere in. Dojrices gravida dignissim. Praesent at nibh in mi fringilla mattis. Phasellus ut dolor odio. Aenean in the ipsum vel lectus bibendum commodo.',
                        text2: 'In nec sem suscipit, convallis leo vitae, lacinia nibh. Cras amet tellus lectus. Vivamus ipsum nunc, mattis quis nibh id, pellentesque arcu. Donec a pellentesque Cras erat enim, gravida non ante vitae,elequis convallis elit, in viverra felis. Donec ultrices tellus vitae iaculisvd porta. Proin tincidunt ligula id purus porttitor.',
                    }
                }
            ],
            showingProjects: [],
          showingArticlesAndNews: [],
        }
    },
    mutations: {
      PUT_IN_SHOWING_PROJECTS (state, pageNumber) {
        const startIndex = (pageNumber-1)*8;
        const endIndex = pageNumber*8;
        state.showingProjects = state.projectsData.slice(startIndex, endIndex);
      },
      PUT_IN_SHOWING_ARTICLES_AND_NEWS (state, pageNumber) {
        const startIndex = (pageNumber-1)*6;
        const endIndex = pageNumber*6;
        state.showingArticlesAndNews = state.articlesAndNews.slice(startIndex, endIndex);
      },
    },
    actions: {
        // Общие действия для выполнения асинхронных операций и коммита мутаций, если необходимо
    },
    getters: {
        getCategories: (state) => state.categories,
        getFollowProjectsData: (state) => state.followProjectsData,
        getStatisticsData: (state) => state.statisticsData,
        getArticlesAndNewsOptions: (state) => state.articlesAndNewsOptions,
        getMainPageStartedImgURL: (state) => state.mainPageStartedImgURL,
        getArticlesAndNews: state => state.articlesAndNews,
        getLargeMainImgs: state => state.largeMainImgs,
        getLatestPostData: state => state.latestPostData,
        getArticlesList: state => state.articlesList,
        getTagList: state => state.tagList,
        getProjectsData: state => state.projectsData,
        getProjectDetailsText: state => state.projectDetailsText,
        getShowingProjects: state => state.showingProjects,
        getNextArrowInBtn: state => state.nextArrowInBtn,
      getShowingArticlesAndNews: state => state.showingArticlesAndNews,
    }
})

export default store
